### ISSUE TITLE
Array naming 

### ISSUE THREAD

**Issue by hclonej** [aichaos/rivescript-python#101]
When i define the array name with undersocre like this:

! array array_name = value value2 value3

rivescipt have a problem with substitute to regex.

Is this a bug? or array name must not include underscore? (I could not find about this in tutorial)

![2017-06-30 6 03 21](https://user-images.githubusercontent.com/9425085/27729409-adad00fc-5dc0-11e7-8169-15b1eddada10.png)

**Comment by kirsle** [comment]
My guess is the `_` is causing problems, but `_` *should* be allowed, so I'll mark this as a bug.

Notes to self or anyone who wants to tackle this bug:

* It might be [this regexp](https://github.com/aichaos/rivescript-python/blob/1f597e8d0aca07b34c6fc5bc7d5a78eb9130c550/rivescript/regexp.py#L25) that needs to change. Check if the `\b` word-boundary matches on `_` characters; if so the regexp might need to be expanded out to `r'\@([A-Za-z0-9_]+'` which I think should match arrays better.
* Debug what's happening [around here](https://github.com/aichaos/rivescript-python/blob/1f597e8d0aca07b34c6fc5bc7d5a78eb9130c550/rivescript/brain.py#L466-L472) (I usually would just add print statements to see what's in those variables), and the [`expand_array`](https://github.com/aichaos/rivescript-python/blob/1f597e8d0aca07b34c6fc5bc7d5a78eb9130c550/rivescript/brain.py#L506-L543) functions.

**Comment by Dinh-Hung-Tu** [comment]
@kirsle I check the array regex and it is not causing the problem here. It is more on whether we would like to parse array with underscore first before treating `_` as special wildcard.

The example here is included in the unit test
```
! array colors_bright = white blue

+ what color is my (@colors_bright) *
- Your <star2> is <star1>.
```
