### ISSUE TITLE
Begin block for simple preprocessing

### ISSUE THREAD

**Issue by staticdev** [aichaos/rivescript-python#114]
I didn't find in the documentation, or in the unit tests how to make the most simple preprocessing: see if the message received is a trigger.

More details: https://stackoverflow.com/questions/48007450/how-to-preprocess-a-special-trigger-in-rivescript-python

**Comment by Dinh-Hung-Tu** [comment]
@staticdev I continue the discussion on Stackoverflow. Please update you example of your expectation of the conversation. I will follow up.

**Comment by staticdev** [comment]
@Dinh-Hung-Tu updated.

**Comment by staticdev** [comment]
Noah Petherbridge answered that (and I updated the answer on Stackoverflow). It is possible to create a topic and make all other one inherit this one, making this preprocessing possible.
