### ISSUE TITLE
Can i set variables in trigger?

### ISSUE THREAD

**Issue by sucream** [aichaos/rivescript-python#119]
hello,

Can i set variables in trigger like this?

```
! array me = me|I
! array you = you|your

+ <set me>(@me)</set>  like <set you>(@you)</set>
- <get me> like <get you>
```

this is just example. so, i want to set var in trigger, and then want to use instead of `<star>`.

Is there way to use like this logic?

**Comment by kirsle** [comment]
That's not supported, but you could put the variable setters in the reply.

```
+ (@me) like (@you)
- <set me=<star1>><set you=<star2>>
^ <get me> like <get you>
```

**Comment by sucream** [comment]
Thanks for your answer.

I wanted to use var like DialogFlow's Intent on google.

and i have another question.

Can i get user's all input in trigger and use it in reply?

I want use like input but not previous inputs.

```
+ * name is *
- you said "<user's all input>"

>>my name is sucream
>>you said "my name is sucream"
```

**Comment by kirsle** [comment]
You can do that with `set_uservar()` from the Python side.

```python
# python
rs.set_uservar(username, "orig_msg", message)
reply = rs.reply(username, message)
```

```java
// rivescript
+ * name is *
- you said "<get orig_msg>"
```

Depending on the environment your bot runs in, you'd probably want to filter the original message first (remove HTML or scripts or any problematic text for the bot's environment).

**Comment by sucream** [comment]
thank you. i understood!
