### ISSUE TITLE
‘=‘ in var definitions ends the definition

### ISSUE THREAD

**Issue by snoopyjc** [aichaos/rivescript-python#130]
If a var definition RHS contains a ‘=‘, that will act as the end of the definition.  Instead it should be part of the variable value.  Example:

    ! var website = https://www.rivescript.com/try/#/doc?x=y&more=more_stuff

    + where is your (website|web site|site)
    - <bot website>

### Bot: https://www.rivescript.com/try/#/doc?x

**Comment by snoopyjc** [comment]
Potential fix in parser.py:

            # Handle the types of RiveScript commands.
            if cmd == '!':
                # ! DEFINE
        -       halves = re.split(RE.equals, line, 2)
        +       halves = re.split(RE.equals, line, 1)

**Comment by snoopyjc** [comment]
Potential fix for js version:

			// Handle the types of RiveScript commands.
			switch (cmd) {
				case "!": // ! Define
		-			let halves = line.split("=", 2);
            +                       let halves = line.split("=", 1);

**Comment by kirsle** [comment]
Fixed in #144.
