### ISSUE TITLE
Python syntax checker gives Unbalanced brackets on nested parens

### ISSUE THREAD

**Issue by snoopyjc** [aichaos/rivescript-python#132]
Nested parens are required to allow permutations of words in a trigger.  Regular expressions handle them just fine, however the parser.check_syntax() method in the Python version (not in JS) is checking for nested parens (and other things) and generating a bogus "Unbalanced brackets" message (which is misleading).  I recommend either removing this check entirely, or just removing parens from the list (and from the total).

Sample valid trigger: `((cat|dog) [*] animal|animal [*] (cat|dog))`

**Comment by kirsle** [comment]
Interesting catch. I looked into this and it seems the outer wrapping parenthesis is what's triggering the error.

The original check_syntax implementation just did a really naive counting of all opening-and-closing brackets and if any came out non-zero at the end, it'd raise an error. This led to [this comment](https://github.com/aichaos/rivescript-python/issues/86#issuecomment-282408186) on #86 showing some example triggers that would _pass_ the syntax check, but produce an invalid regexp, like `)invalid( parenthesis`, `(or <this) thing>`

The change to the Python check_syntax function was added in #103 and it considers it an error to have deeply nested brackets of any kind, with exception for `<` and `>` brackets. The JavaScript and other implementations are still using the original naive algorithm.

I've never officially supported using wrapped groups of capturables the way your example does. RiveScript's "simplified regexp" system is intended for writing simple plain-language triggers, and nested capture groups is a leak in the abstraction around regexps. I think Python's strictness is "more correct" than the other implementations.

You can turn off the syntax checking by passing `strict=False` to the `RiveScript()` constructor.

**Comment by kirsle** [comment]
Fixed in #144.

**Comment by NathanBaulch** [comment]
I just got stung by this one.
It looks like those of us stuck on Python 2 that need nested parens and don't want to disable strict mode need to downgrade to v1.14.7.
