### ISSUE TITLE
Python version doesn't sort triggers properly when multiple [*] are used

### ISSUE THREAD

**Issue by snoopyjc** [aichaos/rivescript-python#133]
With this rivescript:

    + [*] what [*] fram is [*]
    - A1

    + [*] what [*] flow [*] getting [*] reviewed [*] fram is answer type [*]
    - A2

    + hey
    @ what flow getting reviewed fram is answer type

Using the rivescript.com "try it" and typing in "hey" gives you "A2", the proper answer.  Using python shell.py will give you "A1".  Checking the sorting logic shows it sorting 3 stars before 6 stars.  Not what I want it to do.  I need it to match the longer trigger.

**Comment by kirsle** [comment]
Fixed in #144.
