### ISSUE TITLE
Error when installing rivescript manually

### ISSUE THREAD

**Issue by benjaballah** [aichaos/rivescript-python#145]
Hello,
When I try to install rivescript manually I get this message.

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import rivescript
  File "~/rivescript-python/rivescript/__init__.py", line 26, in <module>
    from .rivescript import RiveScript
  File "~/rivescript-python/rivescript/rivescript.py", line 902
    nonlocal user
                ^
SyntaxError: invalid syntax
```

**Comment by snoopyjc** [comment]
What version of Python?

-joe

**Comment by benjaballah** [comment]
I use pyhton 2.7.17

**Comment by snoopyjc** [comment]
Sorry, try 3.6+

“After spreading the news at conferences, on the Python announcement list, and on countless blog posts and books, the Python Software Foundation has finally taken the step to formally announce Python 2 will reach end of life (EOL) on January 1st, 2020.”

**Comment by kirsle** [comment]
Hi @benjaballah,

I second @snoopyjc's comment: Python 2.7 is now end-of-life according to the [Python branch status](https://devguide.python.org/#status-of-python-branches) so future releases of RiveScript won't support Python 2.

The final version of `rivescript-python` with support for Python 2.7 is v1.14.9 which you can still install from pip:

```bash
pip install rivescript==1.14.9
```

For using RiveScript >= 1.15.0 you'll need to upgrade to a recent version of Python 3. I understand upgrading a Python2 codebase isn't always an easy task, but you can safely stick with RiveScript 1.14.9 for the foreseeable future.
