### ISSUE TITLE
Reduce Rivesript Reponse Time

### ISSUE THREAD

**Issue by hankp46** [aichaos/rivescript-python#147]
I'm a noobie with Rivescript and just experimenting. I loaded approximately 70 rive files and ran the example.py script. I found response relatively slow. In AIML you can have a brain that is already "compiled" to speed up response time. Is there a similar feature in Rivescript?

**Comment by snoopyjc** [comment]
Are you using 1.15 because that version has some very good speed improvements?

That said, it’s pretty dependent on the speed of Regex as it uses lots of those to do matching.

**Comment by hankp46** [comment]
After reading the benchmark report it seems rivescript runs very slow in Python vs Node JS. Will attempt to continue using Node js.
