### ISSUE TITLE
no support for accented characters?

### ISSUE THREAD

**Issue by jjoaovitor7** [aichaos/rivescript-python#151]
```
+ olá
- olá!
```

`Exception: Syntax error in ./brain\hello.rive line 1: Triggers may only contain lowercase letters, numbers, and these symbols: ( | ) [ ] * _ # @ { } < > = (near: + olá)`

riverscript doesn't support accented characters?

**Comment by jjoaovitor7** [comment]
oh, I found the solution, utf-8.

```
bot = RiveScript(utf8=True)
```

**Comment by snoopyjc** [comment]
Feliz Navidad!

-joe
