### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by movehoon** [aichaos/rivescript-python#19]
I god error when i input 'comment ça va'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)

I can fix this issue when add a line on rivescript.py (line 1520)

    def reply(self, user, msg, errors_as_replies=True):
        """Fetch a reply from the RiveScript brain."""
        msg = msg.decode('utf8')    #<<<<<<-----------  add this line
        self._say("Get reply to [" + user + "] " + msg)

Please check it.
Thanks

**Comment by kirsle** [comment]
This one was fixed with the above commit. I fixed it in the interactive shell code (rivescript/interactive.py), so that incoming messages from the user are decoded as UTF-8.
