### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by movehoon** [aichaos/rivescript-python#20]
Hi.
I report again similar issue about unicode.

I got error as below when unicode output at return of object
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 0: ordinal not in range(128)

I can fix this issue to add a line at rivescript.py(about 2232 line)

           output = output.decode('utf8')    #<<<<<<------- add this line
            reply = reply.replace('<call>{match}</call>'.format(match=match), output)

**Comment by kirsle** [comment]
What code did you use that reproduces this behavior? I tried the following which reproduced it:

```
> object test python
	return "comment ça va"  # this line breaks in Python 2 only
< object

+ test
- comment ça va<call>test</call>
```

The problem in the above code is actually in the `> object test python` code, which returns an ASCII string containing non-ASCII characters, and it only raises an error on Python 2. In Python 3 strings are unicode by default and the above code doesn't result in an error.

There are two workarounds if you're running RiveScript in Python 2:

1. Make your strings unicode, by putting a letter `u` in front of a quoted string, like `return u"comment ça va"`
2. Handle Unicode escaping yourself (e.g. do the `.decode("utf8")` inside your Python object macros)

Or run your bot in Python 3 if at all possible.

**Comment by movehoon** [comment]
I’m using python2.

Thank you for your answer.
