### ISSUE TITLE
how to get original text which contain special char

### ISSUE THREAD

**Issue by yyken** [aichaos/rivescript-python#25]
for example

```
+ what is *
- <star> is something.
```

user> what is  domain\account
bot  > domainaccount is something

expect reply:  domain\account is something

or

```
+ what is *
- <formal> is something.
```

user> what is  Cindy Wang (IS-TW)
bot  >Cindy Wang (is-Tw) is something

expect reply:  Cindy Wang IS-TW) is something

tks

**Comment by kirsle** [comment]
For the first example:

In the default (non-UTF8) mode, all extra symbols are removed from the user's message after substitutions have been run (`! sub`) on it. In UTF-8 mode, the user's message is left *mostly* intact except for the characters `\`, `<` and `>` (to prevent breaking the regular expression engine and to protect from HTML-based XSS attacks), and any symbols in the `unicodePunctuation` regexp, which is by default the set of `!.,?;:`

So the `\` is being removed from the message in UTF-8 mode. (It could be possible to double-escape the `\` so it doesn't break the regexp engine and then it could be allowed in the message, but currently it just removes that symbol completely).

In your second example: the `<formal>` tag formalizes the `<star>`, making the first letter of each word uppercase and the rest of it lowercase. For the formalizing, the algorithm does this:

* Split the text into words at the space character
* For each word: uppercase the first letter and lowercase the remaining letters

In your example "Cindy Wang (IS-TW)" it does the right thing on the first part, but not the second part. But the formalizing function is working as expected.

As a side note: the user's message always gets made lowercase regardless of UTF-8 mode, and triggers are also lowercase, which is an optimal configuration for matching triggers to messages. Hence the need for `<formal>` etc. tags; but the tags were designed for normal looking names, like `Mr. John Doe`. It doesn't work well for certain titles and suffixes, but these are kinda hard to control for.
