### ISSUE TITLE
When are you adding database Session support to...

### ISSUE THREAD

**Issue by lynxionxs** [aichaos/rivescript-python#31]
When are you going to add support for Database user session variables and rivescript router controllers for python and go ?

**Comment by kirsle** [comment]
Which one is a higher priority for you, Python or Go?

For the router part, that didn't require any change to the internals of rivescript-js, so you should be able to adapt [the example code](https://github.com/aichaos/rivescript-js/blob/f8fce55ac26a467b53640863d99ade96d730e27f/eg/router/router.js#L11-L91) from there into Python or Go. It mostly just came down to a data structure that mapped your triggers to your object macros and then having your code dynamically `stream()` the triggers/replies in and `setSubroutine()` the object macros, both of which are doable in Python and Go already.

For the database session support it's just a matter of making all the internal references to user data go through the `setUservar` etc. methods, and replace the implementation of those methods to use a pluggable session handler class. It wouldn't take too long to do (I did that to the JavaScript one in a couple of hours).

**Comment by lynxionxs** [comment]
Using Python Falcon framework. So its higher priority.
Yes for Router controllers i guess its easy to stream() like in js version.

Since Python is syncronous in nature it should be easier to handle database user session variables.
I think it would be better to add a multi Database/Memory session handler in the Python version core.
This was impossible in the js version since it is asyncronous.
That should make Rivescript-python very scalable across multiple servers.

**Comment by lynxionxs** [comment]
@kirsle could you add the Database/Memory session handler feature to the Rivescript core instead ?
I will have to modify Rivescript every time to be able to do that and mess with pip packages in python.

**Comment by kirsle** [comment]
The support for it will be in the core (there'll be a way to hook your own class in to manage user variables), but the core will only come with an in-memory session handler by default.

**Comment by lynxionxs** [comment]
Yes, that will be perfect. I will add the database session that way.
Thanks.

**Comment by kirsle** [comment]
@lynxionxs I made the session store replaceable in #32 and released v1.14.0 to PyPI which includes this change.

[Here's an example](https://github.com/aichaos/rivescript-python/tree/master/eg/sessions) that uses Redis as the session store. You'll need to write your own to use a database.

At some point in the future I'll make some "more official" modules for popular storage back-ends (Redis, SQLAlchemy for SQLite/MySQL/Postgres) and either release those separately on PyPI or bundle them in the RiveScript module itself (like `from rivescript.sessions.redis import RedisSessionStorage`); haven't decided yet.
