### ISSUE TITLE
Auto user sesson expiry

### ISSUE THREAD

**Issue by lynxionxs** [aichaos/rivescript-python#34]
Hi. Could you please add a session expiry method to the rivescript base session handler, aswell as a core method to set it via the bot object. 
I tried expiring it from outside rivescript session, but that requires another Session instance.
Such a mehod will work great with Redis session. Tia
```python
# rivescript.py

def expire_user(self, user, time):
    """Delete user session when time expires.
        eg. expire Jonny5's session in 10 minutes
        bot.expire_user("Jonny5", 600)
    """
    # set expiry
    self._session.expire(user, time)
    
```

**Comment by kirsle** [comment]
`clear_uservars()` would clear a user's variables. What mechanism would handle automatically expiring vars by calling this method? Also Redis could just expire the keys on its own.
