### ISSUE TITLE
Fuzzy sentence/commands detection

### ISSUE THREAD

**Issue by lynxionxs** [aichaos/rivescript-python#38]
Is it possible to make a fuzzy sentence detection and commands joining system in Rivescript?
Then split each sentence/command individually for triggers and process each.
Eg. Usecases: 
"Tell John there is a meeting tomorrow at 2pm, then check what's the weather"
"Get my last note and order my fav pizza"

Joiners like "and" "then" can be used as split points. Also fuzzy sentence detection like ". " dot space, ". Abc" dot space Uppercase letter etc...

**Comment by kirsle** [comment]
I don't think a feature like this could coexist with the way RiveScript currently works.

I've heard of bot engines that work this way (IIRC, Siri might do something similar), where a user's message of "tell John there is a meeting tomorrow at 2pm" might be broken down into an unsorted list of keywords like, `["tell", "John", "meeting", "tomorrow", "2pm"]`, and for the sake of example that list could also have been randomly sorted like `["2pm", "John", "meeting", "tomorrow", "tell"]`, and the bot would match that to some sort of trigger that mentions all 5 of those words (well, it would know "John" is a name and "2pm" is a time and match those to generic "name" and "time" items, but you get the idea).

A system like this would also benefit a lot from a natural language parser like [nltk](http://www.nltk.org/).

**Comment by lynxionxs** [comment]
I guess its a bit too complex of a feature then. Alot of core refactoring needed and such.
I will have to make my own "front-parser" to split sentences and put each in an array of trigger commands.
Then give that to Rivescript to process.
It can be done without having to use a whole natural language parser like NLTK.
Maybe a wrapper class around Rivescript. 
It will be awesome to make the bot do many tasks via a single command.
