### ISSUE TITLE
Is it possible to create a specific(general trigger) ?

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#39]
hello everyone,
we have general reply for unknown trigger
ex : 

```
+ *
- please, try with other words
```

but i'd like to question like this : 

who is Einstein / what is an apple / how is the fire....

i'd like to create that : 

```
+ who is *
- {@<star>}      # redirects to known trigger (in atomic.learn for example)

+ who *
- I don't know who it is. I can search on wiki if you want,
```

and same for what / how .... to create more realistic replies.

Tried ! and doesn't work

Please help

**Comment by elpimous** [comment]
?? if a request * is not found, what is the value of <star> ? (perhaps i could do a condition ?!)

**Comment by kirsle** [comment]
What doesn't work about it?

The `*` in a trigger usually *has* to match something or else the trigger won't match the user's message. If you had `who is *`, the user has to say "who is (something)", if they just said "who is" it won't match that trigger. The exception is when you put a `*` in square brackets, like `[*]` which makes it an optional wildcard, and those *never* go into `<star>` tags. Those are more useful for "magic word" type triggers, like

```
+ [*] the machine [*]
- How do you know about the machine?
```

**Comment by elpimous** [comment]
thanks for answer, Kirsle, 
Let me explain more...
here is my test : 

+ *               # generic reply
- I don't know your words, or speak loudly, please

+ A
- the letter A

+ B
- the letter B

+ what is letter *
- {@<star>}                 # works nice with A and B, But what if I ask for C ?!!!

+  ????????  What could be the trigger, for this reply on unknown letters ???????
- I don't know this letter !

Thanks friend

**Comment by kirsle** [comment]
The `#` symbol isn't used for comments in RiveScript, replace them with `//` if you want comments in your code.

I updated your code to this:

```
+ *               // generic reply
- I don't know your words, or speak loudly, please

+ a
- the letter A

+ b
- the letter B

+ what is letter *
- {@<star>}                 // works nice with A and B, But what if I ask for C ?!!!

// +  ????????  What could be the trigger, for this reply on unknown letters ???????
// - I don't know this letter !
```

And this gets this result:

```
You> hi
Bot> I don't know your words, or speak loudly, please
You> a
Bot> the letter A
You> b
Bot> the letter B
You> c
Bot> I don't know your words, or speak loudly, please
You> what is letter A  
Bot> the letter A
You> what is letter b
Bot> the letter B
You> what is letter C
Bot> I don't know your words, or speak loudly, please
```

Pro tip: if you turn on debug mode (e.g. by `python shell.py --debug` or using `debug=True` in the constructor) you can see what RiveScript is doing. With your original code, when I said "what is letter c" this is what it did under the hood:

```
You> what is letter c
[RS] Get reply to [localuser] what is letter c
[RS] Checking topic random for any %Previous's.
[RS] There is a %Previous in this topic!
[RS] lastReply: the letter a                  works nice with a and b but what if i ask for c 
[RS] Try to match 'what is letter c' against 'a' ('^a$')
[RS] Try to match 'what is letter c' against 'b' ('^b$')
[RS] Try to match 'what is letter c' against '*               # generic reply' ('^(.+?)               (\\d+?) generic reply$')
[RS] Try to match 'what is letter c' against 'what is letter *' ('^what is letter (.+?)$')
[RS] Found a match!
[RS] Reply: {@<star>}                 # works nice with A and B, But what if I ask for C ?!!!
[RS] Redirect to c
[RS] Try to match 'c' against 'a' ('^a$')
[RS] Try to match 'c' against 'b' ('^b$')
[RS] Try to match 'c' against '*               # generic reply' ('^(.+?)               (\\d+?) generic reply$')
[RS] Try to match 'c' against 'what is letter *' ('^what is letter (.+?)$')
Bot> [ERR: No reply matched]
```

The second to last thing it tried to match against was your `*` trigger, which had the wrong `#` symbol for comments and you can see why it wouldn't match the letter "c".

**Comment by elpimous** [comment]
Ok, thanks friend.
I had the same results..

So I'm sad !!

no possibility to do anything like this ??

+ what is letter *  (or) what is letter [*] or what is letter (*) // ask for unknown letter
- i don't know this letter  // standard reply for this specific topic

Thanks again

**Comment by kirsle** [comment]
The closest to what you wanna do might be to have to spell out all possible versions, and have one with a `*` as the fallback one.

Like:

```
+ a
- The letter A

+ b
- The letter B

+ c
- The letter C

// Here's the two main triggers you sound like you want:
+ what is letter (a|b|c)
@ <star1>

+ what is letter *
- I don't know that letter.

+ *
- The generic fallback for all unmatched messages.
```

There would need to be a bit of redundancy (for each letter that you want to redirect to, you also have to put that letter in the alternation group like `(a|b|c)`), but in this example if somebody said "what is letter D" the bot would say "I don't know that letter." because it ended up matching the `what is letter *` trigger, not the default wildcard `*` trigger.

Alternatively, use an object macro and sort it out there.

```
> object letter python
    letter = args[0]
    if letter in ["a", "b", "c"]:
        return "The letter " + letter
    return "I don't know that letter."
< object

+ what is letter *
- <call>letter <star></call>
```
