### ISSUE TITLE
UTF-8 accents on triggers

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#40]
Hello,
in my 1.14 python version,
and with ai = RiveScript(utf8=True) on my python file,
I can't enter any accents "éèàç..." on question.

here is the error : 

Traceback (most recent call last):
  File "C:\Users\neo\Downloads\rivescript-python\RS_AI.py", line 17, in <module>
    reply = ai.reply("localuser", msg)
  File "C:\Users\neo\Downloads\rivescript-python\rivescript\rivescript.py", line 999, in reply
    return self._brain.reply(user, msg, errors_as_replies)
  File "C:\Users\neo\Downloads\rivescript-python\rivescript\brain.py", line 46, in reply
    self.say("Get reply to [" + user + "] " + msg)
  File "C:\Users\neo\Downloads\rivescript-python\rivescript\brain.py", line 41, in say
    self.master._say(*args, **kwargs)
  File "C:\Users\neo\Downloads\rivescript-python\rivescript\rivescript.py", line 149, in _say
    self._log.write("[RS] " + message + "\n")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 25: ordinal not in range(128)

What did I miss ???

Thanks Kirsle
Vincent

**Comment by elpimous** [comment]
Well, utf8 bool doesn't seems to run ?!

**Comment by kirsle** [comment]
It's a Python 2 Unicode problem, and I can't reproduce it under Python 3. It also seems to be a regression as it used to work in Python 2 in the past.

I looked into it for a while yesterday but it'll require digging deeper into it. Usually it was the case that as long as you make sure your input message is a proper Unicode object (if printing `repr(message)` gave a string beginning with `u'`, for example `u'pok\xe9mon'`) then everything else would work as the code itself uses `unicode_literals`, so interpolating your Unicode string into a quoted string would work fine, but that didn't seem to help this time.

**Comment by kirsle** [comment]
There seemed to be two different problems:

* A couple of the source files did *not* do `from __future__ import unicode_literals`, so I fixed them so they all import this (that fixes the interpolation errors when putting unicode strings into quoted messages for debug logging etc.)
* The interactive mode needed to additionally decode the user's input message into Unicode, but only for Python 2 (in Python 3 the result from `input()` is already Unicode to begin with).

I'll release a fix pretty soon.

**Comment by kirsle** [comment]
Try version [1.14.1](https://pypi.python.org/pypi/rivescript/1.14.1).

**Comment by elpimous** [comment]
hi Kirsle,
last version tested right now,
with python 3 question with accents (écoute moi ça) seems to work. No errors
however, can't enter this trigger : + écoute moi ça

returns : 
    raise Exception(syntax_error)
Exception: Syntax error in ./eg/neo_brain\neo_Questions.rive line 106: Triggers may only contain lowercase letters, numbers, and these symbols: ( | ) [ ] * _ # @ { } < > = (near: + écoute moi)
See you and thanks again for help.
U'll wait for fix. Have a nice day

**Comment by kirsle** [comment]
>  Exception: Syntax error in ./eg/neo_brain\neo_Questions.rive line 106: Triggers may only contain lowercase letters, numbers, and these symbols: ( | ) [ ] * _ # @ { } < > = (near: + écoute moi)

For this you have to use the utf8=True constructor option. By default it won't allow any non-ASCII letters in triggers (accented letters would also be removed from the user's message anyway and would make matching impossible).

**Comment by elpimous** [comment]
Works nice on python 3,
Working on python2 (i try some possibilities)
Thanks
