### ISSUE TITLE
how to change ID (localuser => <get name>)

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#42]
Could you explain how to change user ID on RS python ?! Thanks

**Comment by kirsle** [comment]
```python
data = rs.get_uservars(old_username)
rs.clear_uservars(old_username)
rs.set_uservars(new_username, data)
```

**Comment by elpimous** [comment]
Thanks Noah

**Comment by elpimous** [comment]
I tested everything, and doesn't work
need, on name topic, to change user ID when a named is told, as in my previous post,

Everytimes, it returns 'localuser'
I am lost, Noah.

**Comment by kirsle** [comment]
When you said "localuser" it makes me think you're using this in the RiveScript built-in interactive shell?

The shell isn't "production ready", it's just for testing your bot locally. You're expected to write Python code for your actual bot that will have multiple users on it.

The username is the first parameter to the `reply` function, so you can just set that to anything you want (for example, use the user's screen name or IP address depending on where your bot gets deployed to).

```python
rs.reply("alice", "my name is Alice")
rs.reply("bob", "my name is Bob")

rs.getUservar("alice", "name")  # "Alice"
rs.getUservar("bob", "name")  # "Bob"
```

That example would have two users now in the bot's memory, each with their own user variables.

If you're using the JSON mode of the shell you can provide your own username in the JSON payload ([more info here](http://rivescript.readthedocs.io/en/latest/rivescript.html#module-rivescript.interactive)). The JSON mode of the shell is intended for if you want to use RiveScript from a programming language that has no RiveScript module of its own, in which case you could shell out to the JSON mode to interact with the bot over a pipe. If you're writing your own bot *in* Python, then write your own code to use the module's API and provide a username for each message with whatever name makes sense for where your bot is gonna be running.

**Comment by elpimous** [comment]
Oh, ok  This is logic, now.
I'll do my own python program, so
Thanks Noah
