### ISSUE TITLE
backup actual user vars to file (text file)

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#43]
I'd like to save all vars in a textfile named with the actual user, and call it at startup, when user is named like the textfile.

tested save vars :
> object savevars python
    a = (args)
    id= "".join(a)
    ID= id.encode('utf8')
    vars = rs.get_uservars()
    vars = str(vars)
    file = open("./eg/neo_brain/uservars/"+ID+".save", "w")
    file.write(vars)
    file.close()
< object                           // dic saved in textfile OK !

tested load vars : 
> object loadvars python
    file = open("./eg/neo_brain/uservars/vincent.save", "r")
    a = file.read()
    a = unicode(a)
    file.close()
    rs.set_uservars(a)
< object

Doesn't work !!
set_uservars() may only be called with types (unicode, dict) or (dict<unicode, dict>) but you called it with types (<type 'unicode'>, <type 'NoneType'>)")
Any help ?
Thanks

**Comment by kirsle** [comment]
Look into the `json` module, and put `json.dumps()` and `json.loads()` around those file operations.

**Comment by kirsle** [comment]
```diff
--- your code example
+++ my fixes using JSON

 > object savevars python
+   import json
-   a = (args)
-   id= "".join(a)
-   ID= id.encode('utf8')
-   vars = rs.get_uservars()
+   ID = rs.current_user()
+   vars = rs.get_uservars(ID)
    file = open("./eg/neo_brain/uservars/"+ID+".save", "w")
-   file.write(vars)
+   file.write(json.dumps(vars))
    file.close()
 < object                           // dic saved in textfile OK !

 > object loadvars python
+   import json
+   ID = rs.current_user()
    file = open("./eg/neo_brain/uservars/"+ID+".save", "r")
-   a = file.read()
+   a = json.loads(file.read())
-   a = unicode(a)
    file.close()
-   rs.set_uservars(a)
+   rs.set_uservars(ID, a)
 < object
```

**Comment by elpimous** [comment]
works well. Thanks Noah
