### ISSUE TITLE
get raw message for wildcard logging

### ISSUE THREAD

**Issue by lynxionxs** [aichaos/rivescript-python#45]
Is there a way to get the original user message so to use it in a logWildcard(user, msg) function ?
get_uservar(user, "__history__")["input][0] does not give the current user message while processing the trigger, only the previous one.
This is for logging various wildcards in various topics. So to improve trigger creation.

**Comment by kirsle** [comment]
You could use `setUservar` before getting their reply to set a variable called like "rawMessage" or w/e, and then you can `getUservar(username, "rawMessage")` to retrieve it.

**Comment by lynxionxs** [comment]
That is strange. I set setUservar(username,"rawMessage", message) in the main script. Then getUservar(username,"rawMessage") in the wildcard trigger , but it returns the previous message.

**Comment by lynxionxs** [comment]
My bad. I was setting the "rawMsg" variable after bot.reply(user, message) . 
Setting it before that fixed it.
