### ISSUE TITLE
Adding global NER models

### ISSUE THREAD

**Issue by rmdort** [aichaos/rivescript-python#50]
Hello Noah, 

I am trying to use [https://spacy.io](https://spacy.io) NLP library with rivescript to get entities from the user's input

````
> object getEntities python
    import spacy
    en_nlp = spacy.load('en')
    return en_nlp(input, entities) /* Example */
````

The issue is that Spacy or any other NLP programs takes a few seconds to load the model, which delays the output of rivescript.

Is it possible to load all the models during initialization of rivescript and set `en_nlp` as a global variable, accessible in all python functions?

**Comment by kirsle** [comment]
You should be able to attach it as your own custom attribute on the RiveScript instance maybe?

```python
import spacy
en_nlp = spacy.load('en')

bot = RiveScript()
bot.spacy_en_nlp = en_nlp
```

```
> object getEntities python
    return rs.spacy_en_nlp(input, entities)
< object
```

Or use any other method of sharing code globally (e.g. have it import a class you make which in turn inputs spacy; RiveScript attempting to re-import your class should use the cached copy of your class iirc)

**Comment by rmdort** [comment]
Awesome. That solves it :) . Thanks @kirsle
