### ISSUE TITLE
access to {topic=reponse1}{@name}   with python ?!

### ISSUE THREAD

**Issue by elpimous** [aichaos/rivescript-python#52]
Hi all, 
need to access to this topic via python 2.4.
anything like rs.???
I didn't find the answer.
Thanks friends
Vincent
PS, Noah, thanks for regular updates.

**Comment by kirsle** [comment]
```python
rs.set_uservar(username, "topic", "response1")
rs.reply(username, message)
```

?

Not sure what the question is.

**Comment by elpimous** [comment]
Yes, perfect
Thanks, Noah
