### ISSUE TITLE
Simple task not working: changing to a topic from inside another topic

### ISSUE THREAD

**Issue by TheRobotCarlson** [aichaos/rivescript-python#55]
When inside a topic, in certain situations, you can't switch to another topic, it would seem.

https://play.rivescript.com/s/FSRc1zPjSA

I've tried multiple workarounds to no success. Everything just stopped working seemingly randomly.

The docs say it [should work this way](https://www.rivescript.com/docs/tutorial#topics) and the examples provided seem to show the [same thing happening](https://github.com/aichaos/rivescript-python/blob/master/eg/brain/rpg.rive)

Am I doing something blatantly wrong or is this a real issue?

**Comment by ekt1701** [comment]
I asked aichaos the same question and he said "the tutorial's code is wrong :wink: when I do stuff like that I use a separate variable, so in the begin condition I do" `* <get met> == undefined => <set met=true>{topic=new_user}{ok}`

**Comment by TheRobotCarlson** [comment]
Thank you so much! Had a demo today and changed the begin last night and couldn't figure out what was happening!

**Comment by kirsle** [comment]
Sorry! I need to fix that tutorial. ;)

**Comment by kirsle** [comment]
The example code in the tutorial was fixed: https://www.rivescript.com/docs/tutorial#the-begin-block

```diff
diff --git a/www/docs/tutorial.md b/www/docs/tutorial.md
index 134ee5a..cb0f23b 100644
--- a/www/docs/tutorial.md
+++ b/www/docs/tutorial.md
@@ -1019,7 +1019,7 @@ Begin Block to introduce itself to new users and interview them:
 
       // If we don't know their name, set the new_user topic and continue.
       + request
-      * <get name> == undefined => {topic=new_user}{ok}
+      * <get met> == undefined => <set met=true>{topic=new_user}{ok}
       - {ok}
 
     < begin
```
