### ISSUE TITLE
Know which file contains the trigger

### ISSUE THREAD

**Issue by Seraf** [aichaos/rivescript-python#6]
Hello,
I don't know if it's usefull to be included in the master branch, but I wonder if it's possible to know in which file is loaded a specific trigger.

Example : I split my project in plugins. Each plugin contains a a rivescript file containing triggers, call/answers.

I would like to know before calling the reply() (and retrieve the answer) which trigger will be ran and in which file. As it is loaded in memory and not know the source file, I don't know if it's possible.
My goal is to do a rule-engine which will be able to modify the message before sending it to reply() IF it match a specific plugin.

Thanks

**Comment by yyken** [comment]
Hi,

i get bellow error at rivescript==1.14.9

code
```python
    reply = bot.reply("localuser", msg)
    last = bot.last_match("localuser")
    print ("Last match:", str(last))
    info = bot.trigger_info(last)
    print(info)
    for idx, info in enumerate(info):
        print("\n<Matched %d>:" % (idx + 1))
        print("  Trigger: %s" % info["trigger"])
        print("  Category: %s" % info["category"])
        print("  Topic: %s" % info["topic"])
        print("  Filename: %s:%d" % (info["filename"], info["line"]))
```

output

```
Last match: vpn
None
Traceback (most recent call last):
  File "./rsbot.py", line 33, in <module>
    for idx, info in enumerate(info):
TypeError: 'NoneType' object is not iterable
```
