### ISSUE TITLE
Exception: Syntax error about italian letters. Triggers may only contain lowercase letters, numbers, and these symbols:

### ISSUE THREAD

**Issue by matteoredaelli** [aichaos/rivescript-python#75]
I would like to use the common italian letters è,é,ò,à,ì,ù .. but I get

Exception: Syntax error in test/z_last.rive line 14: Triggers may only contain lowercase letters, numbers, and these symbols: ( | ) [ ] * _ # @ { } < > = (near: + è il cap di xxxx)

**Comment by kirsle** [comment]
It should work in UTF-8 mode by using the `utf8=True` param to the constructor.

**Comment by matteoredaelli** [comment]
It works, thanks
