### ISSUE TITLE
Resetting Tree

### ISSUE THREAD

**Issue by jayrav13** [aichaos/rivescript-python#81]
Hi there,

A question re: the topic tree - let's say I have a server running and I want to reset the tree without the server restarting - is there a way to purge the tree and then do, let's say, `load_directory(...)` or `stream(...)` again?

**Comment by kirsle** [comment]
Not currently but contributions are welcome. :smile:

**Comment by snoopyjc** [comment]
Oh I was able to code this in my bot - it's not easy - I call it "brain_transplant".  I'll see if I can put it in the code base.

**Comment by kirsle** [comment]
Fixed in #144.
