### ISSUE TITLE
Syntax error: Piped optionals check

### ISSUE THREAD

**Issue by Dinh-Hung-Tu** [aichaos/rivescript-python#87]
This code is not allowed in RiveScript-JS version 1.17.2
```
+ hello [|]
- hi
```
Syntax error: Piped optionals can't begin or end with a | at stream() line 1 near + hello [|]
But this error check is not detected in Python version. In Python, this pair matches the word hello exactly, without any additional word.

**Comment by Dinh-Hung-Tu** [comment]
I look at the code to identify where the empty option is parsed in brain.py [L447](https://github.com/aichaos/rivescript-python/blob/master/rivescript/brain.py#L447). It shows that the list of parts (after splitting by |) is not checked for empty string. 
```        
# Optionals.
optionals = re.findall(RE.optionals, regexp)
for match in optionals:
    parts = match.split("|")
    new = []
    for p in parts:
        p = r'(?:\\s|\\b)+{}(?:\\s|\\b)+'.format(p)
        new.append(p)
```
This bug does no harm if we miss empty options. However if we want to place a check for empty string here, check_syntax function alone doesn't check this bug. This is only uncovered during the replacement of our symbols (i.e. wildcards by its corresponding Regex).

With this finding, can you suggest what to do here? Do you want to parse the optional during the check_syntax (like JS version)?

**Comment by kirsle** [comment]
Yeah it would be nicer to get the versions to all behave the same. The JavaScript version picked up the "empty pipe check" somewhere along the way [via pull request #101](https://github.com/aichaos/rivescript-js/pull/101), and the other versions didn't get updated to follow. Feel free to open a PR to apply the update to the Python version. :smile:
