### ISSUE TITLE
Improve ranking algorithm for triggers with no words

### ISSUE THREAD

**Issue by Dinh-Hung-Tu** [aichaos/rivescript-python#94]
1. Issue: The current sorting algorithm fails again when the trigger with no text (trigger 2 below) takes precedence over the trigger with text (trigger 1). This undesired sorting is not seen in both Python release [v1.14.4](https://github.com/aichaos/rivescript-python/releases/tag/v1.14.4) (prior to new sorting algorithm) and JavaScript version (tested in https://www.rivescript.com/try).
```
+ hi [*]
- 1
+ _ _
- 2
```

2. Explanation of the behaviour: This is because the binary presence of words (yes, no) is not taken properly. This was handled with star such that single star `*` and its variance `[*]` would be placed last in the sorting. 
3. Solution: Create a new variable to indicate the presence of words. Make this the first sorting criteria. Within each group (with and without words), we apply the old sorting algorithm.

**Comment by Dinh-Hung-Tu** [comment]
The change in this issue would also change the ranking order of `[*]` and `*`, which is recently handled in #92. Since the two triggers are serving the same purpose (match any string including empty one), they should not appear in the same script, therefore the order between them is not strict as long as they both secure the last places in the ranking.

**Comment by kirsle** [comment]
Fixed in PR #95
